import type { Metadata } from "next"
import ImageDetector from "@/components/image-detector"

export const metadata: Metadata = {
  title: "AI Image Detector",
  description: "Upload an image to detect if it was generated by AI",
}

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-4 bg-gradient-to-b from-gray-50 to-gray-100">
      <div className="w-full max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-800">AI Image Detector</h1>
          <p className="text-gray-600 mt-2">Upload an image to detect if it was generated by AI</p>
        </div>
        <ImageDetector />
      </div>
    </main>
  )
}
